### ISSUE TITLE
processing of ATCOR file

### ISSUE THREAD

**Issue by wilsonphl1234** [lbusett/prismaread#2]
Hi, may i know what is the process of ATCOR and how to insert the ATCOR data into the PRISMA imagery ?

**Comment by ranghetti** [comment]
Hi, unfortunately Lorenzo, who developed the package {prismaread}, has recently passed away (https://docs.ropensci.org/MODIStsp/articles/lorenzo.html). I will replace him in the maintainance of the package, but for the moment I do not know the code yet.
For now you can have a look to the documentation at https://lbusett.github.io/prismaread/articles/prismaread .
If you will found the answer by yourself, can you please provide the answer for future reference?
Thank you

**Comment by ranghetti** [comment]
{prismaread} does not launch / make use of ATCOR, but can produce text files to be used for launching ATCOR (separately). You can find the reference here: https://lbusett.github.io/prismaread/articles/Importing-Level-1-Data.html#creation-of-atcor-files
I something is not clear, please reopen the issue.
